package com.springmvc.web.admin.entity;

import com.springmvc.web.forum.entity.JForum;
import com.springmvc.web.person.entity.Person;

import javax.persistence.*;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;

// Generated 2015-6-23 2:24:27 by Hibernate Tools 4.0.0

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin")
public class Admin implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
    @Column(name="id")
    @GeneratedValue
    private Integer id;
    @Column(name="name")
	private String name;
    @Column(name="password")
	private String password;


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admin",cascade = CascadeType.ALL)

	private Set<JForum> jforums=new HashSet<JForum>(0);

	@ManyToMany(mappedBy = "admin",cascade = CascadeType.PERSIST)
	private Set<Person> personSet=new HashSet<Person>(0);

	public Set<Person> getPersonSet() {
		return personSet;
	}


	public Admin() {
	}

	public Admin(String name, String password,Set jforums) {
		this.name = name;
		this.password = password;
		this.jforums=jforums;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}



	public Set getJforums() {
		return jforums;
	}

	public void setJforums(Set jforums) {
		this.jforums = jforums;
	}

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

}
